name: CI

on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: ./checkly

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "12.x"
      - run: npm install
        # working-directory: checkly
      - run: npm run build:prod
        # working-directory: checkly
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
